### ISSUE TITLE
Why is that?

### ISSUE THREAD

**Issue by uselessgoddess** [linksplatform/Incrementers#30]
Why is that?https://github.com/linksplatform/Incrementers/blob/d48eda0625c3756e3fbea54ac580d135400b737f/csharp/Platform.Incrementers/Incrementer%5BTValue%2C%20TDecision%5D.cs#L28-L33
If there is this
https://github.com/linksplatform/Incrementers/blob/d48eda0625c3756e3fbea54ac580d135400b737f/csharp/Platform.Incrementers/Incrementer%5BTValue%2C%20TDecision%5D.cs#L21-L26

**Comment by Konard** [comment]
To ignore the value, as I remember, just increment and return true :)
